### ISSUE TITLE
How to quantize and built with Metal support for this model? 

### ISSUE THREAD

**Issue by laosuan** [guinmoon/LLMFarm#1]
https://huggingface.co/openllmplayground/openalpaca_3b_600bt_preview

**Comment by guinmoon** [comment]
To support metal, I need to update the sources of llama. When I do this I will try to load openllama with metal.

**Comment by laosuan** [comment]
Got it, built with metal support seem need a lot of work. 

I found the following program commands on https://github.com/ggerganov/llama.cpp, Can I put this model(openllmplayground/openalpaca_3b_600bt_preview) quantize in this way?

# quantize the model to 4-bits (using q4_0 method)
./quantize ./models/7B/ggml-model-f16.bin ./models/7B/ggml-model-q4_0.bin q4_0

**Comment by guinmoon** [comment]
[there is](https://huggingface.co/guinmoon/LLMFarm_Models/resolve/main/openllama-3b-350bt-ggml_v3-q4_0.bin) a quantization model that works fine with this application

**Comment by laosuan** [comment]
Thanks, I tried these code, it worked. but I found some little problem:
1. It does not support generate according to history of conversation.
2. It seems need a function to clean the conversation.

By the way, I recommend an excellent mini model: https://twitter.com/erhartford/status/1672672018779766784

**Comment by guinmoon** [comment]
Thanks for the tip, good model. I'm working on context support like interactive mode in llama.cpp

**Comment by aehlke** [comment]
Please update llama.cpp again - they've recently landed improvements for OpenML + Metal together for the fastest perf yet
