### ISSUE TITLE
Why Extended Virtual Addressing Entitlement required?

### ISSUE THREAD

**Issue by siisee11** [guinmoon/LLMFarm#11]
Thanks for the amazing project!

I removed Extended Virtual Addressing Capability and built because it requires developer account which I don't have.
And It works. Why this capacity is required?

**Comment by guinmoon** [comment]
Extended Virtual Addressing and increased-memory-limit entitlements is required to run models `larger than 3B`, otherwise the application may crash. If for some reason you cannot build an application with this entitlement, you can simply `turn it off`.
