### ISSUE TITLE
Adding support for Mistral

### ISSUE THREAD

**Issue by rodas-j** [guinmoon/LLMFarm#12]
I just want to say I love what you are doing and I'm happy I stumbled upon this repo. 

Is it possible to add support for Mistral AI?

https://huggingface.co/mistralai/Mistral-7B-v0.1

**Comment by guinmoon** [comment]
I have mistral running fine on macOS. 
Prompt format: 
`[INST] {{prompt}} [/INST]`
![Screenshot 2023-10-08 at 22 15 43](https://github.com/guinmoon/LLMFarm/assets/3720051/b9ef5664-5abf-4f27-aedf-0589962c3feb)

**Comment by rodas-j** [comment]
I was trying to run Q2 quantized models on xcode simulator and I run into errors. Maybe I'm trying something that's not possible.

![Simulator Screenshot - iPhone 15 Pro - 2023-10-08 at 16 52 56](https://github.com/guinmoon/LLMFarm/assets/50768698/407501a7-4c8f-4e14-b39a-5b1fabcd17e0)

![Simulator Screenshot - iPhone 15 Pro - 2023-10-08 at 17 12 48](https://github.com/guinmoon/LLMFarm/assets/50768698/a76a721d-875f-434f-9580-6ab3bc4bf6ef)

**Comment by guinmoon** [comment]
Maybe there is something wrong with the model file?
![Screenshot 2023-10-09 at 06 39 14](https://github.com/guinmoon/LLMFarm/assets/3720051/6abc99b7-effd-4769-a744-f21c8724a399)
![Screenshot 2023-10-09 at 06 37 58](https://github.com/guinmoon/LLMFarm/assets/3720051/5473d290-6772-4936-a1a5-cc0282332b9d)

**Comment by rodas-j** [comment]
I got it to work. You are right. Thanks!
