### ISSUE TITLE
When I send out my first prompt to llm after opening the app, The app will freeze for like 5-10 seconds before llm generate the response.

### ISSUE THREAD

**Issue by steveshaoucsb** [guinmoon/LLMFarm#15]

**Comment by guinmoon** [comment]
The moment you send the first message, the model is loaded. This is done because usually more than 1 model cannot fit in the device memory, and in order not to lose context when switching chat, the model is loaded only when the first message is sent. I will add animation later.

**Comment by steveshaoucsb** [comment]
Roger that thanks for the explanation!
