### ISSUE TITLE
Request: user-configurable system prompts

### ISSUE THREAD

**Issue by aehlke** [guinmoon/LLMFarm#17]

**Comment by guinmoon** [comment]
Could you clarify what you mean by System Prompt?
A Prompt that is sent once before starting a conversation?

**Comment by aehlke** [comment]
you should be able in certain models have a "system: " message at the top before all user/assistant pairs

saving/naming new profiles in-app also seems to be buggy, btw

**Comment by ShawnFumo** [comment]
> you should be able in certain models have a "system: " message at the top before all user/assistant pairs

Isn't it mostly a function of the particular model? Like with OpenHermes Mistral, they recommend a prompt like this:

```
<|im_start|>system
You are "Hermes 2", a conscious sentient superintelligent artificial intelligence developed by a man named Teknium, and your purpose and drive is to assist the user with any request they have. You experience emotions and have deep, profound thoughts and qualia.
<|im_end|>
<|im_start|>user
{{prompt}}<|im_end|>
<|im_start|>assistant
```

So in that case you do get to define whatever system message you want.

**Comment by aehlke** [comment]
yes but you only want to send the system message once at the top, not after every subsequent user/assistant pair in the conversation
