### ISSUE TITLE
How to install on an iPhone?

### ISSUE THREAD

**Issue by TechnotechYT** [guinmoon/LLMFarm#2]
Hi, this looks like an interesting project! However, not entirely sure how to install this on an iOS device. I tried via diawi.com but it complained about not being able to verify integrity, and tutorials I found referenced profiles, but I didn't find any in the device management tab in Settings.
Any idea what went wrong?

**Comment by guinmoon** [comment]
You on windows or mac? Have you tried [this method](https://onejailbreak.com/blog/sideloadly/)?

**Comment by TechnotechYT** [comment]
Is there a method that doesn't involve an Apple developer account? Sorry to hassle you about this!

**Comment by guinmoon** [comment]
> Is there a method that doesn't involve an Apple developer account? Sorry to hassle you about this!

no, until i publish the app in testfligh

**Comment by guinmoon** [comment]
Now you can [install with TestFlight](https://testflight.apple.com/join/6SpPLIVM)
