### ISSUE TITLE
Token to string issue FYI

### ISSUE THREAD

**Issue by aehlke** [guinmoon/LLMFarm#20]
You may be interested in this: https://github.com/ggerganov/llama.cpp/pull/4325

**Comment by Cojad** [comment]
I'm experienceing utf-8 string issue, too. 

shown in Screenshot:
![231216_2224_chrome](https://github.com/guinmoon/LLMFarm/assets/5554735/73052e10-8166-4fe4-8089-0a1b5c88e6d7)

**Comment by guinmoon** [comment]
Thanks for the feedback. I will try to fix the errors in new versions.
