### ISSUE TITLE
Clear chat, edit previous messages

### ISSUE THREAD

**Issue by ShawnFumo** [guinmoon/LLMFarm#22]
Hi, thanks for all your work on this project! There are cases where it'd be nice to be able to clear the entire chat history (without having to create a whole new chat from scratch) and/or edit/delete previous messages in a conversation.

Btw, there is that button at the top with a counter-clockwise circling arrow (and touching it gives a check mark), but not sure what it actually does if anything?

Edit: Or if there was a way to duplicate the current chat setup or some other way to easily have multiple threads going at once, that could help for chat management.

**Comment by ebolamerican** [comment]
I thought it was the "clear context" button (i.e., starts the conversation over, but without clearing the prior chat history.

If that's not what it is, then I don't actually know what it is. 😂

**Comment by ShawnFumo** [comment]
> I thought it was the "clear context" button (i.e., starts the conversation over, but without clearing the prior chat history.
> 
> 
> 
> If that's not what it is, then I don't actually know what it is. 😂

Oh that could be!
