### ISSUE TITLE
Fine tuning does not work

### ISSUE THREAD

**Issue by solidityenthusiast** [guinmoon/LLMFarm#24]
Hi, I'm using LLMFarm testflight on M1 Max with 64 GB RAM. I cannot get fine-tuning to run. When I click the run button, nothing happens in the UI. Is there something I'm missing?

For reference, I'm trying to train mistral-7b-instruct-v0.2 on 1,000 rows of a *.JSONL file. I have also tried a basic *.TXT file and *.JSON array file, but neither worked. Changing the params or toggling "Metal" didn't help either.

Any ideas?

**Comment by guinmoon** [comment]
Unfortunately, it looks like fine tuning can only be done for models with `llama` architecture at the moment.
Could you send a screenshot of what you see when you click "run finetune"?

**Comment by guinmoon** [comment]
If finetune is running you should see something like this
![Screenshot 2023-12-16 at 11 42 00](https://github.com/guinmoon/LLMFarm/assets/3720051/9ea6f67f-f253-4dce-97dc-d6879f01b490)

**Comment by solidityenthusiast** [comment]
Hey @guinmoon, I'm not getting any output in the logs. No CPU usage in activity monitor. I am on the latest testflight. Any idea what could be going wrong? See the video below:

https://github.com/guinmoon/LLMFarm/assets/95111407/c02ec66c-c0a3-4b37-9114-053c89c629b2

**Comment by guinmoon** [comment]
That's weird. It's not supposed to be like that. I'll look into it.

**Comment by jasjeev4** [comment]
I tried the same on my M1 Pro Macbook as well as my iPhone 15 Pro and I too don't see logs when I run fine tuning.

**Comment by jasjeev4** [comment]
I believe it's due to a commented line which disables the file from being created. Changing it fixes it for me: 

https://github.com/guinmoon/LLMFarm/pull/34

**Comment by guinmoon** [comment]
Can you tell me if this problem still occurs in the new version?

**Comment by kebbbnnn** [comment]
Had the same issue. The reason was my fine tuning dataset was on my mac's Download folder instead of the "datasets" folder of the app that's why [get_path_by_short_name()](https://github.com/guinmoon/LLMFarm/blob/be9b2e8d3124f7c2cbbcb1ceefd96d88ac0700de/LLMFarm/Tune/FineTuneModel.swift#L76) function returned nil path aborting the finetuning. Make sure everything is in the right place.
