### ISSUE TITLE
stablelm-zephyr-3b-GGUF model fails to load

### ISSUE THREAD

**Issue by gblazex** [guinmoon/LLMFarm#25]
https://huggingface.co/TheBloke/stablelm-zephyr-3b-GGUF

Both on iphone and mac, so it must be a problem with the program

no descriptive error message just "model failed to load"

Mistral 7b works fine.

**Comment by guinmoon** [comment]
Hi. I downloaded the Q4_K_M version and I have everything working. Could you please send me a screenshot of the settings?

**Comment by gblazex** [comment]
<img width="774" alt="Screenshot 2023-12-16 at 12 01 48" src="https://github.com/guinmoon/LLMFarm/assets/309987/ac6fdf10-d7cd-4cf4-b391-70e1954decfd">
just default llama settings

<img width="243" alt="Screenshot 2023-12-16 at 12 02 19" src="https://github.com/guinmoon/LLMFarm/assets/309987/cb7f0e17-d761-476c-a407-0570cbdfbfb8">

**Comment by gblazex** [comment]
any logging i can send you?

**Comment by guinmoon** [comment]
Are you using application version 0.8.1?

**Comment by gblazex** [comment]
okay I got it to work with 0.8.1 good tip! (i had 0.8.1 on phone from testflight but mac version was from app store).

Question is how to set up prompt format. E.g. for this model it says:

```
<|user|>
List 3 synonyms for the word "tiny"<|endoftext|>
<|assistant|>
1. Dwarf
2. Little
3. Petite<|endoftext|>
```
https://huggingface.co/TheBloke/stablelm-zephyr-3b-GGUF#usage

Prompt, reverse prompt, special, BOS, EOS

How can you set these up?

**Comment by gblazex** [comment]
This is what I used, but not sure if how your app would add `<|endoftext|>`
```
<|user|>
{{prompt}}<|endoftext|>
<|assistant|>
```

There is EOS (End-of-sequence?) switch but doesn't let me specify what that token looks like.

**Comment by guinmoon** [comment]
> <|user|>
> {{prompt}}<|endoftext|>
> <|assistant|>

Try using this template with:
BOS - false
EOS - false
Special - true
reverse - <|endoftext|>

I'll post a wiki about the options later.

**Comment by gblazex** [comment]
Yes that would be great! Because these options don't always work perfectly.

e.g. "You have 5 apples. You eat 2 and give 1 to a friend. How many apples do you have left?"

```
You start with 5 apples.
You eat 2, so you have 5 - 2 = 3 apples left.
Then you give 1 to a friend, so you have 3 - 1 = 2 apples left.
#### 2
The answer is: 2
```

I tried in LM Studio and that ending shouldn't be there. 
this looks like a prompt splitting issue -----> #######
