### ISSUE TITLE
Phi-2 does not work

### ISSUE THREAD

**Issue by willfaust** [guinmoon/LLMFarm#29]
Please update llama.cpp to version [b1658](https://github.com/ggerganov/llama.cpp/releases/tag/b1658) or any other release after commit [b9e74f9](https://github.com/ggerganov/llama.cpp/commit/b9e74f9bca5fdf7d0a22ed25e7a9626335fdfa48). This should allow Microsoft's [Phi-2](https://huggingface.co/microsoft/phi-2) 2.7B model to work.

**Comment by GoWithitRoger** [comment]
Is phi-2 planned to be supported? It seems to be the most promising small model at the moment, no?

**Comment by guinmoon** [comment]
I plan to update llama.cpp to support Phi-2 in the LLMFarm 0.9.0 release

**Comment by willfaust** [comment]
Sounds good! I’m excited to test the performance.
