### ISSUE TITLE
The latest code simulator crash

### ISSUE THREAD

**Issue by buhe** [guinmoon/LLMFarm#36]
Nice project.

## Env

iphone 15 iOS 17.0
M1 max
xcode Version 15.2 (15C500b)

## Log
[log.txt](https://github.com/guinmoon/LLMFarm/files/14006285/log.txt)

**Comment by buhe** [comment]
![Uploading Simulator Screenshot - iPhone 15 Pro - 2024-01-22 at 15.06.47.png…]()

**Comment by buhe** [comment]
![Uploading 截屏2024-01-22 下午3.07.42.png…]()

**Comment by buhe** [comment]
Testflight version is work with metal.

**Comment by guinmoon** [comment]
to run on the simulator you need to turn off the metal, later I will write a check for this in the code.

**Comment by buhe** [comment]
But i use real device: iphone 12

**Comment by guinmoon** [comment]
Hi I had a similar problem on my iphone 12 pro. Apparently the app crashed because the debugging information also takes up some memory space. Try to use a smaller model and read [this article](https://alwaysprocessing.blog/2022/02/20/size-matters).

**Comment by buhe** [comment]
Thanks.
