### ISSUE TITLE
Dolphin models problem (modelLoadError)

### ISSUE THREAD

**Issue by BlobIsBack** [guinmoon/LLMFarm#38]
They just doesn't seems to work, so far tested phi 2 dolphin and mistral 7b dolphin and it don't work. Maybe I'm just dumb, if that's the case can someone give me a step by step guide on how to use phi 2 dolphin ? (I'm using TestFlight version and iPhone XR)

**Comment by BlobIsBack** [comment]
Btw sorry for my bad English, I'm French

**Comment by rd-neosoft** [comment]
I was able to run [phi2](https://huggingface.co/TheBloke/phi-2-GGUF/blob/main/phi-2.Q4_K_M.gguf) on iphone 15 pro but not able to run the same model on iphone XR

**Comment by BlobIsBack** [comment]
Still the same problem

**Comment by guinmoon** [comment]
> I was able to run [phi2](https://huggingface.co/TheBloke/phi-2-GGUF/blob/main/phi-2.Q4_K_M.gguf) on iphone 15 pro but not able to run the same model on iphone XR

Iphone XR only has 3GB RAM, so try using q3_k_s quantization, might be able to get it to run.
