### ISSUE TITLE
Sampling stuck in greedy

### ISSUE THREAD

**Issue by Maw1979** [guinmoon/LLMFarm#42]
The sampling is reverted back to greedy if I try to change it. Device: iPhone 15 pro max

In greedy mode the app is unusable. The llm keeps inferencing.

**Comment by Maw1979** [comment]
I have tried tiny llama 1.1b 4K_M and mistral 7b 0.1 4K_M. The problem is the configuration itself. No matter what I try the settings are not saved. Even when trying different templates it is reverted back to custom with the greedy setting.![image](https://github.com/guinmoon/LLMFarm/assets/159609715/06c8769b-4e6c-40ee-802f-8c596ff80cd0)

**Comment by Maw1979** [comment]
I just tried the app on a iPhone 14 Pro Max. Although the template also reverts back to custom, the settings are applied. 

The answers on the 15 pro max are completely random and incoherent. But this is probably because of the temperature settings?

**Comment by guinmoon** [comment]
I am thinking about your question, but so far I have not been able to reproduce this bug.

**Comment by Maw1979** [comment]
I can get it to work now on the 15 pro. When I choose the llama2 7b iPhone 12 template and don't change anything, it works. The sampling setting stays on temperature. However, the template setting reverts back to custom.

**Comment by guinmoon** [comment]
Can you tell me if this problem still occurs in the new version?
