### ISSUE TITLE
Apple Model Available

### ISSUE THREAD

**Issue by lawyinking** [guinmoon/LLMFarm#45]
Is anyone willing to list the Apple models and corresponding hardware details (e.g. RAM) that can run the listed LLM models using LLM Farm? If so that would be great.

Many thanks!

**Comment by guinmoon** [comment]
Hi, some tests of llama.cpp, which is the basis for LLMFarm, can be seen [here.](https://github.com/ggerganov/llama.cpp/discussions/4508)

**Comment by lawyinking** [comment]
Thank you so much!
