### ISSUE TITLE
Few feature requests..

### ISSUE THREAD

**Issue by ProCreations-Offical** [guinmoon/LLMFarm#46]
Firstly, I’d love to see the ability to save the downloaded LLM’s to be saved on external drives. I tried to download an AI on my SSD but, when I loaded onto LLM Farm, it copied the file and placed it into On My iPhone >> LLM Farm >> Models. (In other words, I want it so I get to choose where the LLM is downloaded and saved instead of being fixed to LLM Farm >> Models). Secondly, I would love to see iOS Siri Shortcuts integration. Lastly, I couldn’t seem to get the Qwen AI model to work. No matter how hard I tried and how much I looked, it kept giving errors.

**Comment by ProCreations-Offical** [comment]
@guinmoon

**Comment by guinmoon** [comment]
Maybe someday I'll realize it all.
The Qwen models have been discussed [here](https://github.com/guinmoon/LLMFarm/issues/49).

**Comment by ProCreations-Offical** [comment]
> Maybe someday I'll realize it all. The Qwen models have been discussed [here](https://github.com/guinmoon/LLMFarm/issues/49).

Thanks for the reply! I’ll take a look at the qwen thing.
