### ISSUE TITLE
It's so slow

### ISSUE THREAD

**Issue by KittenYang** [guinmoon/LLMFarm#49]
LLMFarm speed:

<img width="110" alt="截屏2024-03-13 01 37 29" src="https://github.com/guinmoon/LLMFarm/assets/5517281/69c28a32-14f0-4e77-805e-75220a30aa93">

---

[Jan](https://github.com/janhq/jan) speed: 
<img width="146" alt="截屏2024-03-13 01 37 38" src="https://github.com/guinmoon/LLMFarm/assets/5517281/2ec07912-3033-4fa1-96c1-7790bef4ce9c">

**Comment by guinmoon** [comment]
Can you tell me what your parameters are for the test? Model, device, prompt?

**Comment by KittenYang** [comment]
Model: https://huggingface.co/Qwen/Qwen1.5-7B-Chat-GGUF
Prompt: Who are you?
Device: M1 Mac
Settings:
<img width="363" alt="截屏2024-03-13 01 50 31" src="https://github.com/guinmoon/LLMFarm/assets/5517281/2274b822-172c-495c-95d0-42e75e2bd35d">

**Comment by guinmoon** [comment]
Very strange results. I have an old intel xeon for 30$ and on it without Metal I have this result. It should be much faster with Metal. 
![Screenshot 2024-03-12 at 21 37 38](https://github.com/guinmoon/LLMFarm/assets/3720051/0b547861-7f95-43de-8992-c8687de86038)
![Screenshot 2024-03-12 at 21 37 03](https://github.com/guinmoon/LLMFarm/assets/3720051/6dfc43dd-52f6-4b41-930e-ddc16c47444b)

**Comment by KittenYang** [comment]
I figure out why.  When I disable the **BOS** in `Prompt format` section, it works like a charm. What's the **BOS**, **EOS** means? 
BTW the same model running on iPhone14 Pro 16.6.1, speed: 0.56token/s, is it normal?
![截屏2024-03-13 10 54 34](https://github.com/guinmoon/LLMFarm/assets/5517281/8ac2c299-5804-46d2-87a5-505fe31d8c90)

**Comment by guinmoon** [comment]
BOS - adds the beginning of session token to the beginning of the message
EOS - adds end of session token to the end of the message
It used to be necessary to add these tokens to some models like LLaMA and Alpaca, now things have changed a bit.
7B models are too big for iphones below 15 pro due to not enough RAM, so will be very slow.

**Comment by KittenYang** [comment]
Thanks man, LLMFarm is really good!
