### ISSUE TITLE
Bugs and suggestions

### ISSUE THREAD

**Issue by FrostyMisa** [guinmoon/LLMFarm#50]
iPhone 15PM, latest LLM FARM version (1.0.0).

Start with bugs:
(Solved) 1: Downloaded mobile VLM 3b model and clip model. Connect them together, set template mobile VLM. Import picture, write in prompt describe this picture. Get correct answer. Import another picture, ask same question, get answer with mixed both answer. Expect this, because the model remember the history. But, clean the chat history with eraser icon, insert another picture, ask the same question, but again, get mixed answer with both the latest picture. 

Expected behavior: it will look only for the text on the window. But it still "remember" the history. You must reload the whole model. 

2: When you generate text, you long hold on the generated text, there is copy, if you click it and paste it back to the prompt line, nothing is pasted (because nothing was copied). 

3: When I edit the VLM model, where I added clip, the clip model doesn't show there and the clip switch is turned off. But when you click the switch, it will load the clip model. So it's there, only the switch is bugged.

4: Same with setting template, you set something, save it, but when return, there is custom showed.

(Solved) 5: When downloading model from the list in app, I tried OpenHermes mistral 7b, select Q4_K_S from the list, but the model downloaded was Q4_K_M. I don't check other models, if there is same "problem".

6: When portrait picture is imported, it's showed like landscape picture after send it to the app. (iPhone screen shot doesn't do it, but photos from back camera do it). 

Now suggestion:
1: It will be nice, when the text still generating, we can scroll up and read the beginning. Now it auto scroll and you cannot interrupt it.

**Comment by guinmoon** [comment]
Hi. Thanks for the feedback! 
At the moment the clear history button does not really clear the model context. You can clear the context by using the reload model button next to the clear button. 
You are not the first to comment on this behavior, so I will add context clearing when clearing history in the new version of the application.
About scrolling, I am aware of this problem and as soon as I get my hands on it I will solve it.

**Comment by FrostyMisa** [comment]
Bug 1 and 5 solved. 
Suggestion 1 partially solved.

When generating text, you cannot scroll the text when keyboard is open, but when you close it with tap, after you can freely scroll it while generating and even when you reopen the keyboard, you can scroll the text.
