### ISSUE TITLE
Issue with LLAVA 1.5

### ISSUE THREAD

**Issue by ProCreations-Offical** [guinmoon/LLMFarm#51]
Hey again, I downloaded a quantized GGUF file for LLAVA 1.5 7b, what would be the prompt format and settings to turn on to use multimodal features? I can’t seem to find it no matter how hard I look.

**Comment by ProCreations-Offical** [comment]
Never mind, I found it, have a good day!

**Comment by tomasmcm** [comment]
@ProCreations-Offical care to share? Can't seem to find a way to add an image besides the shortcut here https://github.com/guinmoon/LLMFarm/blob/main/docs/shortcuts.md

**Comment by ProCreations-Offical** [comment]
> @ProCreations-Offical care to share? Can't seem to find a way to add an image besides the shortcut here https://github.com/guinmoon/LLMFarm/blob/main/docs/shortcuts.md

I have been summoned! You need to add a CLIP. Open the models settings, toggle on the Clip setting, find and add the clip file for the llava model you're using, and then try it.

**Comment by tomasmcm** [comment]
@ProCreations-Offical Ah, the great summoning has worked! I shall add the CLIP and unleash the power of my LLava model, and then we can ride off into the sunset on a llama-powered unicycle, my friend 😊

**Comment by aiakubovich** [comment]
Where are guys find clip model? I downloaded llava model from here https://huggingface.co/xtuner/llava-llama-3-8b-v1_1-gguf/blob/main/llava-llama-3-8b-v1_1-int4.gguf  . I look at clip repo https://huggingface.co/openai/clip-vit-large-patch14-336/tree/main but it is not clear what file is needed

**Comment by aiakubovich** [comment]
It looks like I was able to find clip file https://huggingface.co/xtuner/llava-llama-3-8b-v1_1-gguf/blob/main/llava-llama-3-8b-v1_1-mmproj-f16.gguf. How do I add image? When I click on + it says "No Photos"
![Screenshot 2024-08-08 at 1 25 41 AM](https://github.com/user-attachments/assets/0a256fe1-ad7a-44cf-8aca-c5d620d4a4ac)
