### ISSUE TITLE
Support for Phi-3 models

### ISSUE THREAD

**Issue by retteghy** [guinmoon/LLMFarm#58]
see [huggingface](https://huggingface.co/collections/microsoft/phi-3-6626e15e9585a200d2d761e3) for the models

**Comment by guinmoon** [comment]
Hi. work normal with this template
```

<|user|>
{{prompt}}<|end|>
<|assistant|>

```
And BOS option enabled.

**Comment by paulilioaica** [comment]
Hi. How can I make it generate until EOS? If I select the option, the app crashes.

**Comment by retteghy** [comment]
> Hi. work normal with this template
> 
> ```
> 
> <|user|>
> {{prompt}}<|end|>
> <|assistant|>
> ```
> 
> And BOS option enabled.

BOS is enabled, I have set that prompt, but I am getting an error as reply for every message:
Load Model Error: [Error]
modelLoad Error
Load Model Error: [Done]

**Comment by guinmoon** [comment]
development version

**Comment by Cimplex** [comment]
> > Hi. work normal with this template
> > ```
> > 
> > <|user|>
> > {{prompt}}<|end|>
> > <|assistant|>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And BOS option enabled.
> 
> BOS is enabled, I have set that prompt, but I am getting an error as reply for every message: Load Model Error: [Error] modelLoad Error Load Model Error: [Done]

In the TestFlight version I’m using ‘Phi-3-mini-4k-instruct-q4.gguf’

When setting up, I used the “Phi 2” setting template and then wrote the recommended prompt. On my iPhone 14 Pro I’m getting around 2-5 token per second.

Sometimes the <|end|> tag isn’t handle correctly, and it just skips over it and starts a new answer
![IMG_8352](https://github.com/guinmoon/LLMFarm/assets/664988/fc542284-d13c-4fc6-9091-04ce0bfd1115)

**Comment by savkinavmono** [comment]
Make sure Metal is on. And try setting contextsize=1024. I got 8-9 Tok/sec.
