### ISSUE TITLE
Can you add tinydolphin 

### ISSUE THREAD

**Issue by EnderRobber101** [guinmoon/LLMFarm#61]
https://www.ollama.com/library/tinydolphin

**Comment by guinmoon** [comment]
You can use this template. BOS = on.
```
[system](You are Dolphin, a helpful AI assistant.)
<|im_start|>user
{{prompt}}<|im_end|>
<|im_start|>assistant
```
![Screenshot 2024-04-30 at 15 58 48](https://github.com/guinmoon/LLMFarm/assets/3720051/e9e3543f-d9ff-4d89-a525-f327826d3dd6)
