### ISSUE TITLE
App crashes when running fine tune on Llama-3

### ISSUE THREAD

**Issue by kebbbnnn** [guinmoon/LLMFarm#62]
App crashes when I run fine tune on Llama-3 model but works perfectly when I try on tinyllama:

Thread 16: EXC_BAD_ACCESS (code=2, address=0x16b5a7c40)

![Screenshot 2024-05-17 at 11 25 02 AM](https://github.com/guinmoon/LLMFarm/assets/4963227/4cea87a2-24d1-4231-b762-834133d43311)

![Screenshot 2024-05-17 at 11 26 21 AM](https://github.com/guinmoon/LLMFarm/assets/4963227/e1566d9a-8312-4d34-a977-9d4bd79ef183)

info of my machine:

mac: mac mini m1 2020
ram: 8GB
os: ventura 13.6
Xcode: Xcode 15.1

**Comment by guinmoon** [comment]
I think it has to do with lack of memory. Llama3 is too big for finetune on your Mac. Try openllama 3b.
