### ISSUE TITLE
Prompt format for SeaLLM model?

### ISSUE THREAD

**Issue by duyluandethuong** [guinmoon/LLMFarm#64]
I'm trying to use this model: https://huggingface.co/SeaLLMs/SeaLLM-7B-v2.5-GGUF

The SeaLLM-7B-v2.5 has the following preset for LM studio: https://huggingface.co/SeaLLMs/SeaLLM-7B-v2.5-GGUF/blob/main/seallm-v2.5.preset.json

I don't know how to convert this into prompt format for LLMFarm. Please help.

When I try to run in Xcode, in print the following lines

<img width="1816" alt="Screenshot 2024-05-19 at 10 52 14 AM" src="https://github.com/guinmoon/LLMFarm/assets/12383199/daf89896-256c-4cf0-b0f5-e8497715fcad">

**Comment by guinmoon** [comment]
Try this: BOS = false, EOS = false
```
[system](<|im_start|>system
You are a helpful assistant.)
<eos><|im_start|>user
{prompt}<eos><|im_start|>assistant

```

stop words = `<|im_start|>;<eos>`

**Comment by guinmoon** [comment]
Tell me this template helped you?
