### ISSUE TITLE
Add support for adjusting --n-predict N

### ISSUE THREAD

**Issue by win1010525** [guinmoon/LLMFarm#65]
![IMG_0288](https://github.com/guinmoon/LLMFarm/assets/50404193/88b6533f-8e8a-43ae-a194-d4a8fc305139)
I hope we can adjust --n-predict N to control the length of the generated text.

**Comment by guinmoon** [comment]
I'll try to add it in new versions.

**Comment by guinmoon** [comment]
done

**Comment by win1010525** [comment]
Thanks!
