### ISSUE TITLE
Feature Suggestion: CoreML/Neural engine

### ISSUE THREAD

**Issue by EnderRobber101** [guinmoon/LLMFarm#69]
Have you considered using CoreML to access the neural engine? I thought it would boost speeds. Thanks!

**Comment by guinmoon** [comment]
`llama.cpp` only uses Metal at the moment.  And LLMFarm is completely based on llama.cpp. The reasons why the Neural engine is not used can be found [here](https://github.com/ggerganov/llama.cpp/discussions/336).
