### ISSUE TITLE
Crashes on iPhone app via Testflight with Dolly v2 and Pythia model

### ISSUE THREAD

**Issue by nehap27** [guinmoon/LLMFarm#7]
Hi,
Thanks for the code. I downloaded the app via Testflight on my iPhone device (iPhone 14Pro, iOS 17). 
I tried to chat with Models Dolly v2 and Pythia, but the app crashed after asking 'How is the weather today?'. 
Attaching the chat and history json here.
[dolly-v2-3b-ggml_v3-q5_1_1695278118.txt](https://github.com/guinmoon/LLMFarm/files/12681460/dolly-v2-3b-ggml_v3-q5_1_1695278118.txt)

[dolly-v2-3b-ggml_v3-q5_1_1695278118.txt](https://github.com/guinmoon/LLMFarm/files/12681463/dolly-v2-3b-ggml_v3-q5_1_1695278118.txt)

[pythia-70m-ggml_v3-q5_1_1695277588.txt](https://github.com/guinmoon/LLMFarm/files/12681450/pythia-70m-ggml_v3-q5_1_1695277588.txt)

**Comment by guinmoon** [comment]
> Hi,
> 
> Thanks for the code. I downloaded the app via Testflight on my iPhone device (iPhone 14Pro, iOS 17). 
> 
> I tried to chat with Models Dolly v2 and Pythia, but the app crashed after asking 'How is the weather today?'. 
> 
> Attaching the chat and history json here.
> 
> [dolly-v2-3b-ggml_v3-q5_1_1695278118.txt](https://github.com/guinmoon/LLMFarm/files/12681460/dolly-v2-3b-ggml_v3-q5_1_1695278118.txt)
> 
> 
> 
> [dolly-v2-3b-ggml_v3-q5_1_1695278118.txt](https://github.com/guinmoon/LLMFarm/files/12681463/dolly-v2-3b-ggml_v3-q5_1_1695278118.txt)
> 
> 
> 
> [pythia-70m-ggml_v3-q5_1_1695277588.txt](https://github.com/guinmoon/LLMFarm/files/12681450/pythia-70m-ggml_v3-q5_1_1695277588.txt)
> 
> 

Based on what I saw in the files, you chose the wrong inference. dolly and pythia need to be run with gptneox inference not with llama
