### ISSUE TITLE
Support ChatML template?

### ISSUE THREAD

**Issue by actow** [guinmoon/LLMFarm#71]
The Qwen2 models uses ChatML.

See https://huggingface.co/Qwen/Qwen2-7B-Instruct/blob/main/tokenizer_config.json

**Comment by actow** [comment]
Also:

https://github.com/ollama/ollama/blob/main/templates/chatml.gotmpl

**Comment by guinmoon** [comment]
Hi.
You can manually create such a template.

BOS = false, EOS = false
```
[system](<|im_start|>system
You are a helpful assistant.)
<eos><|im_start|>user
{prompt}<eos><|im_start|>assistant

```

stop words = `<|im_start|>,<eos>`

**Comment by yangtuo250** [comment]
My template:

BOS = false, EOS = false, Special = true

Format:

```

<|im_start|>system
You are a helpful assistant.
<eos>
<|im_start|>user
{prompt}<eos>
<|im_start|>assistant

```

Skip tokens:
`<|im_start|>,<eos>`

Metal = true

**Comment by actow** [comment]
thanks a lot. It will be even better if that becomes a built-in template. Given that Qwen2 is gaining popularity and it has 0.5b and 1.5b models, I'd imagine this can be useful to many people.

**Comment by actow** [comment]
Also, is there a way to import templates?

**Comment by yangtuo250** [comment]
> Also, is there a way to import templates?

For iPhone, iust put json file in "File" App -> My iPhone -> LLM Farm -> model_setting_templates.

**Comment by actow** [comment]
That worked. Thanks a lot.
