### ISSUE TITLE
Add in-app option support for flash attention

### ISSUE THREAD

**Issue by DKNTZMN** [guinmoon/LLMFarm#76]
Please add a support of in-app flash attention option for the model. Current model is spitting nonsense while running without flash attention. Thank you.

**Comment by MiniPhantom** [comment]
You can enable it in the json chat settings file I’m pretty sure.

**Comment by DKNTZMN** [comment]
> You can enable it in the json chat settings file I’m pretty sure.
I’ve been using iOS version of LLM farm. Not sure what are you talking about.
