### ISSUE TITLE
Aya-23-8B gibberish if metal AND mmap turned on

### ISSUE THREAD

**Issue by mounta11n** [guinmoon/LLMFarm#77]
Hi there, i wanted to run Aya-23-8B from cohere on the iPad pro 12,9“ M1, since Aya is an excellent multilingual llm. It turned out that it gives me gibberish whenever **metal and mmap** is turned on at the **same time**. I i tried it a lot of times with different configurations. It seems to be independent from which prompt format and other options. It it is only metla-AND-mmap dependent.

If **metal=OFF and mmap=OFF**, the time until first token is very long, but it gives me coherent answers, but very very slow (like ~0,15 t/s ).

If **metal=OFF and mmap=ON**, the time until first token is short (so seems mmap is really on) and it gives me coherent answers, but very very slow (like ~0,15 t/s ).

If **metal=ON and mmap=OFF**, it gives me coherent and correct answers at **~8 t/s**.

If **metal=ON AND mmap=ON**, it spit out only **gibberish**, and interestingly much **faster** than the case before. Here I get **12 t/s** for some reason.

—-

I have been using
- Aya-23-8B-Q4_K_S.gguf
- iPad pro 12,9“ M1
- iPad-OS 18.0 Developer Beta
- LLMFarm 12.5 from Testflight
- Various Prompt Formats

—-

### metal=off mmap=off

![IMG_0645](https://github.com/guinmoon/LLMFarm/assets/123123600/6408a444-ee63-4459-985a-7fc89302c8b7)

### metal=on mmap=on

![IMG_0646](https://github.com/guinmoon/LLMFarm/assets/123123600/384f6e80-6a91-48ea-8e2b-f23cf64258cb)

**Comment by guinmoon** [comment]
Hi. What version of LLMFarm are you using?

**Comment by mounta11n** [comment]
I tried it with:

- v. 1.2.0 (Appstore)
- v. 1.2.5 (Testflight)

**Comment by savkinavmono** [comment]
Hi. 
What prompt format are you using?

Try this:
```
<|START_OF_TURN_TOKEN|><|USER_TOKEN|>{prompt}<|END_OF_TURN_TOKEN|><|START_OF_TURN_TOKEN|><|CHATBOT_TOKEN|><|END_OF_TURN_TOKEN|><|START_OF_TURN_TOKEN|><|CHATBOT_TOKEN|>
```

**Comment by mounta11n** [comment]
I think I was already using this prompt format. And note that in the two pictures above the configs are exactly the same, only mlock was turned off in the first picture and turned on in the second picture.
