### ISSUE TITLE
Gemma-2-2b-it crashing

### ISSUE THREAD

**Issue by IneffableBunch** [guinmoon/LLMFarm#84]
iOS 16.0
iPhone 12

I have a q4 gguf, but everytime I try to start, it crashes.

**Comment by guinmoon** [comment]
Hi. Gemma2 is not supported yet, but I will add it soon. I need to update llama.cpp to add support for gemma2.

**Comment by delfer** [comment]
Привет! Огромное спасибо за этот проект! Жду поддержки Gemma2 с нетерпением!

**Comment by guinmoon** [comment]
done
