### ISSUE TITLE
Eval error often appear when using llama 2

### ISSUE THREAD

**Issue by steveshaoucsb** [guinmoon/LLMFarm#9]
When I ask llama 2 after the it successfully generated an answer, or when it is in the process of generating long answers, it will always shows up “Eval error” and I need to restart the app to let the llama 2 work again.
![image](https://github.com/guinmoon/LLMFarm/assets/56005374/d7d4cf39-1db2-4531-bfb5-05b80952510e)

**Comment by guinmoon** [comment]
try increasing the context size to 2048

**Comment by steveshaoucsb** [comment]
> try increasing the context size to 2048

Thanks! Now that error disappeared, but the new problem is that the llama 2 doesn't finished the answer and apparently aborted at some point. Here are examples:![image](https://github.com/guinmoon/LLMFarm/assets/56005374/476a5e61-1ff9-4e92-b429-9e4f9ec59ada)
![image](https://github.com/guinmoon/LLMFarm/assets/56005374/85671f55-3379-4677-8c1f-9a2843ee2dce)

**Comment by guinmoon** [comment]
That's weird. The dialog is terminated without an error only if llama generates an end-of-session token. If you continue the conversation, will it continue normally or with an error?

**Comment by steveshaoucsb** [comment]
It just continue without showing obvious error message, other than the conversation ends early.
![image](https://github.com/guinmoon/LLMFarm/assets/56005374/cfff9c2b-28ee-42d3-b0a8-4f2137be131a)

**Comment by guinmoon** [comment]
Tell me, did the update solve the problem?

**Comment by guinmoon** [comment]
Can you send me the text of the request? I'll try it myself.

**Comment by guinmoon** [comment]
I think I found what the problem was. Tell me, did the update solve the problem?

**Comment by steveshaoucsb** [comment]
> I think I found what the problem was. Tell me, did the update solve the problem?

It fixed!
