### ISSUE TITLE
llama 3.2 Support

### ISSUE THREAD

**Issue by KTRosenberg** [guinmoon/LLMFarm#94]
Llama 3.2 was just announced, but do you anticipate updating this project with an example using the small llama 3.2 on-device models, standalone on an iPad?

**Comment by brunodoamaral** [comment]
I was able to run the [Llama-3.2-1B-Instruct-Q8_0.gguf](https://huggingface.co/lmstudio-community/Llama-3.2-1B-Instruct-GGUF/tree/main) with llama inference on an iPhone Pro Max 13, using the TestFlight version.

I just need to tune the prompt format, but it worked at about 20 t/s. Very nice!

**Comment by KTRosenberg** [comment]
It would be good to have some installation instructions though. I'm definitely looking forward to seeing how this runs on-device / how fast it is (the small version).

**Comment by HaysianSmelt** [comment]
It should be able to run fine on an Iphone. the 3B model at 8bit flys on a samsung 24+

**Comment by KTRosenberg** [comment]
How would you integrate the on-device model within an existing xcode project, however? This would be for an iPad. It'd be great to have instructions on how to do this. Probably it should be built externally and dropped-in to avoid coupling with projects.

**Comment by guinmoon** [comment]
llmfarm 1.3.9 now supports llama 3.2. Currently only text models.
